In [3]:
!pip3 install pandas

Requirement already satisfied: pandas in /Users/theroyakash/Developer/GitHub/packing-coloring/RandomDegreeBoundedGraphs/.venv/lib/python3.12/site-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.26.0 in /Users/theroyakash/Developer/GitHub/packing-coloring/RandomDegreeBoundedGraphs/.venv/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/theroyakash/Developer/GitHub/packing-coloring/RandomDegreeBoundedGraphs/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/theroyakash/Developer/GitHub/packing-coloring/RandomDegreeBoundedGraphs/.venv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/theroyakash/Developer/GitHub/packing-coloring/RandomDegreeBoundedGraphs/.venv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Users/theroyakash/Developer/GitHub/packing-coloring/RandomDegreeBoundedGraphs/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [26]:
four_degree_bound = "../stastistics/stats_4.csv"
five_degree_bound = "../stastistics/stats_5.csv"


import pandas as pd

In [38]:
df4 = pd.read_csv(four_degree_bound, sep = ',', index_col=False)

In [39]:
df4.head()

,CaseID,Nodes,Edges,Packing Coloring Start Time,Duration,Max Reusable Color ID,Total Colors Used,Unique Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves
0,1,6930,6929,6,0.236011 seconds,479,479,0,n/14,4112,1303,59.3362%,3446
1,2,9393,9392,37,0.274033 seconds,642,642,0,n/14,5559,1786,59.1824%,4650
2,3,9243,9242,6,0.26134 seconds,608,608,0,n/15,5547,1713,60.013%,4670
3,4,6938,6937,6,0.138271 seconds,460,460,0,n/15,4146,1301,59.7579%,3458
4,5,5816,5815,54,0.0885575 seconds,367,367,0,n/15,3462,1107,59.5254%,2879

In [55]:
df5 = pd.read_csv(five_degree_bound, sep = ',', index_col=False)

In [56]:
df5

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves
0,1,6219,6218,8,0.13859 seconds,402,n/15,3698,1158,59.4629%,3094
1,2,7528,7527,11,0.18179 seconds,495,n/15,4488,1410,59.6174%,3763
2,3,7129,7128,2,0.16021 seconds,477,n/14,4279,1299,60.0224%,3600
3,4,8747,8746,7,0.25595 seconds,621,n/14,5206,1595,59.5175%,4406
4,5,5872,5871,48,0.107242 seconds,412,n/14,3486,1097,59.3665%,2921
5,6,5661,5660,4,0.0987107 seconds,402,n/14,3363,1062,59.4065%,2831
6,7,7275,7274,1,0.171437 seconds,517,n/14,4339,1346,59.6426%,3666
7,8,9373,9372,18,0.261865 seconds,608,n/15,5618,1731,59.9381%,4757
8,9,8469,8468,10,0.23856 seconds,580,n/14,5049,1582,59.6174%,4212
9,10,6082,6081,9,0.110259 seconds,408,n/14,3636,1108,59.783%,3073

In [53]:
ten_degree_bound = "../stastistics/stats_10.csv"
df10 = pd.read_csv(ten_degree_bound, sep = ',', index_col=False)

df10

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves
0,1,6968,6967,6,0.144332 seconds,454,n/15,4169,1301,59.8307%,3510
1,2,9943,9942,14,0.318606 seconds,617,n/16,5925,1852,59.5897%,4956
2,3,9635,9634,18,0.290576 seconds,629,n/15,5762,1793,59.8028%,4846
3,4,6892,6891,26,0.158339 seconds,462,n/14,4123,1278,59.823%,3463
4,5,8047,8046,14,0.200834 seconds,545,n/14,4808,1484,59.749%,4056
5,6,8073,8072,15,0.215422 seconds,545,n/14,4783,1496,59.2469%,3999
6,7,7859,7858,118,0.191214 seconds,512,n/15,4684,1471,59.6005%,3907
7,8,6705,6704,15,0.123045 seconds,436,n/15,3984,1263,59.4183%,3345
8,9,8103,8102,37,0.221566 seconds,561,n/14,4797,1535,59.2003%,3990
9,10,6698,6697,12,0.130773 seconds,446,n/15,3955,1262,59.0475%,3328

### 50000 - 100,000 Nodes
Stats for graphs with 50,000 to 100,000 nodes. Degree bound is set to 4.

In [57]:
df_50_100 = pd.read_csv("../stastistics/stats_50_100.csv", sep = ',', index_col=False)
df_50_100

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves
0,1,93232,93231,1,38.6065 seconds,6084,n/15,55619,17328,59.6566%,46611
1,2,59529,59528,23,15.868 seconds,3842,n/15,35530,11111,59.6852%,29755
2,3,93377,93376,325,36.1935 seconds,5967,n/15,55639,17456,59.5853%,46563
3,4,88866,88865,68,31.9109 seconds,5703,n/15,53018,16569,59.6606%,44465
4,5,52332,52331,27,10.8482 seconds,3357,n/15,31180,9765,59.5811%,26108

In [61]:
df_50_100['Total Leaves to Color 1 Count Ratio'] = df_50_100['Total Leaves'] / df_50_100['Color 1 Count']
df_50_100

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves,Total Leaves to Color 1 Count Ratio
0,1,93232,93231,1,38.6065 seconds,6084,n/15,55619,17328,59.6566%,46611,0.838041
1,2,59529,59528,23,15.868 seconds,3842,n/15,35530,11111,59.6852%,29755,0.837461
2,3,93377,93376,325,36.1935 seconds,5967,n/15,55639,17456,59.5853%,46563,0.836877
3,4,88866,88865,68,31.9109 seconds,5703,n/15,53018,16569,59.6606%,44465,0.838677
4,5,52332,52331,27,10.8482 seconds,3357,n/15,31180,9765,59.5811%,26108,0.837332

In [62]:
df10['Total Leaves to Color 1 Count Ratio'] = df10['Total Leaves'] / df10['Color 1 Count']

In [63]:
df10

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves,Total Leaves to Color 1 Count Ratio
0,1,6968,6967,6,0.144332 seconds,454,n/15,4169,1301,59.8307%,3510,0.841929
1,2,9943,9942,14,0.318606 seconds,617,n/16,5925,1852,59.5897%,4956,0.836456
2,3,9635,9634,18,0.290576 seconds,629,n/15,5762,1793,59.8028%,4846,0.841027
3,4,6892,6891,26,0.158339 seconds,462,n/14,4123,1278,59.823%,3463,0.839922
4,5,8047,8046,14,0.200834 seconds,545,n/14,4808,1484,59.749%,4056,0.843594
5,6,8073,8072,15,0.215422 seconds,545,n/14,4783,1496,59.2469%,3999,0.836086
6,7,7859,7858,118,0.191214 seconds,512,n/15,4684,1471,59.6005%,3907,0.834116
7,8,6705,6704,15,0.123045 seconds,436,n/15,3984,1263,59.4183%,3345,0.839608
8,9,8103,8102,37,0.221566 seconds,561,n/14,4797,1535,59.2003%,3990,0.831770
9,10,6698,6697,12,0.130773 seconds,446,n/15,3955,1262,59.0475%,3328,0.841466

In [64]:
ddf = pd.read_csv("../stastistics/stats.csv", sep = ',', index_col=False)

In [65]:
ddf

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves
0,1,88781,88780,9,32.8491 seconds,5766,n/15,52957,16569,59.649%,44384
1,2,67058,67057,8,17.5949 seconds,4290,n/15,39967,12487,59.6006%,33500
2,3,95175,95174,18,36.9358 seconds,6066,n/15,56766,17767,59.6438%,47558
3,4,95147,95146,39,37.2082 seconds,6133,n/15,56771,17720,59.6666%,47531
4,5,84382,84381,12,28.4715 seconds,5318,n/15,50309,15712,59.6205%,42156