In [1]:
import pandas as pd

In [23]:
deg_three_bound = pd.read_csv("../stastistics/stats_3.csv", sep=',', index_col=False)
deg_three_bound["leaves/ratio"] = deg_three_bound["Total Leaves"] / deg_three_bound["Nodes"] * 100
deg_three_bound

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves,leaves/ratio
0,1,35843,35842,33,0.532999 seconds,394,n/90,19803,7733,55.2493%,13636,38.043691
1,2,47575,47574,18,0.792474 seconds,511,n/93,26268,10307,55.2139%,18167,38.186022
2,3,29586,29585,13,0.31961 seconds,325,n/91,16342,6390,55.2356%,11270,38.092341
3,4,26204,26203,15,0.25451 seconds,299,n/87,14495,5613,55.316%,10018,38.230804
4,5,37777,37776,29,0.588651 seconds,431,n/87,20849,8117,55.1897%,14452,38.256082

In [24]:
deg_three_bound_10_cases = pd.read_csv("../stastistics/stats_10-3.csv", sep=',', index_col=False)
deg_three_bound_10_cases["leaves/ratio"] = deg_three_bound_10_cases["Total Leaves"] / deg_three_bound_10_cases["Nodes"] * 100
deg_three_bound_10_cases

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves,leaves/ratio
0,1,44106,44105,9,0.664595 seconds,460,n/95,24350,9540,55.2079%,16857,38.219290
1,2,29399,29398,13,0.320329 seconds,324,n/90,16230,6364,55.206%,11299,38.433280
2,3,19829,19828,24,0.143609 seconds,234,n/84,10956,4286,55.2524%,7570,38.176408
3,4,10323,10322,3,0.0394277 seconds,141,n/73,5696,2240,55.1778%,3932,38.089703
4,5,13796,13795,15,0.0722418 seconds,169,n/81,7617,2991,55.2117%,5290,38.344448
5,6,25038,25037,49,0.214447 seconds,262,n/95,13860,5390,55.3559%,9662,38.589344
6,7,49302,49301,29,0.907608 seconds,509,n/96,27215,10691,55.2006%,18785,38.101903
7,8,16802,16801,1,0.147636 seconds,210,n/80,9259,3631,55.1065%,6432,38.281157
8,9,38467,38466,16,0.564482 seconds,408,n/94,21236,8326,55.2058%,14722,38.271765
9,10,10752,10751,21,0.0431531 seconds,143,n/75,5936,2330,55.2083%,4088,38.020833

In [25]:
deg_four_bound = pd.read_csv("../stastistics/stats_10-4.csv", sep=',', index_col=False)
deg_four_bound["leaves/ratio"] = deg_four_bound["Total Leaves"] / deg_four_bound["Nodes"] * 100
deg_four_bound

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves,leaves/ratio
0,1,30567,30566,4,1.74976 seconds,1148,n/26,17637,6070,57.6995%,13952,45.643995
1,2,45313,45312,2,3.75265 seconds,1676,n/27,26131,9000,57.6678%,20700,45.682255
2,3,34129,34128,4,1.85074 seconds,1211,n/28,19686,6786,57.6812%,15525,45.489173
3,4,18509,18508,23,0.547518 seconds,694,n/26,10688,3669,57.7449%,8425,45.518396
4,5,32707,32706,15,1.94331 seconds,1229,n/26,18771,6527,57.3914%,14870,45.464274
5,6,47345,47344,1,3.95162 seconds,1776,n/26,27256,9449,57.5689%,21490,45.390221
6,7,19997,19996,11,0.73358 seconds,804,n/24,11484,3984,57.4286%,9135,45.681852
7,8,27281,27280,2,1.2939 seconds,1025,n/26,15691,5414,57.5162%,12405,45.471207
8,9,49136,49135,87,4.4364 seconds,1841,n/26,28281,9791,57.5566%,22430,45.648811
9,10,16974,16973,31,0.537599 seconds,656,n/25,9758,3375,57.4879%,7790,45.893720

In [26]:
deg_five_bound = pd.read_csv("../stastistics/stats_10-5.csv", sep=',', index_col=False)
deg_five_bound["leaves/ratio"] = deg_five_bound["Total Leaves"] / deg_five_bound["Nodes"] * 100
deg_five_bound

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves,leaves/ratio
0,1,27696,27695,11,2.12347 seconds,1404,n/19,16223,5339,58.5752%,13327,48.118862
1,2,47984,47983,38,6.20615 seconds,2482,n/19,28143,9193,58.6508%,23172,48.291097
2,3,38448,38447,9,4.23243 seconds,1957,n/19,22526,7445,58.5882%,18466,48.028506
3,4,21553,21552,1,1.24437 seconds,1148,n/18,12633,4126,58.6137%,10362,48.076834
4,5,37684,37683,3,4.31422 seconds,1945,n/19,22148,7202,58.773%,18239,48.399851
5,6,24029,24028,10,1.7243 seconds,1249,n/19,14053,4659,58.4835%,11539,48.021141
6,7,46103,46102,10,6.8412 seconds,2342,n/19,27061,8832,58.6968%,22220,48.196430
7,8,30406,30405,29,2.39924 seconds,1572,n/19,17818,5849,58.6003%,14625,48.099059
8,9,38109,38108,14,3.85268 seconds,1924,n/19,22405,7311,58.7919%,18393,48.264190
9,10,32804,32803,3,2.86852 seconds,1661,n/19,19253,6298,58.691%,15830,48.256310

In [27]:
d6b = pd.read_csv("../stastistics/stats_10-6.csv", sep=',', index_col=False)
d6b["leaves/ratio"] = d6b["Total Leaves"] / d6b["Nodes"] * 100
d6b

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves,leaves/ratio
0,1,42364,42363,51,5.5468 seconds,2446,n/17,25045,8067,59.1186%,20781,49.053442
1,2,49597,49596,30,8.06327 seconds,2919,n/16,29266,9427,59.0076%,24395,49.186443
2,3,38312,38311,6,4.71983 seconds,2179,n/17,22579,7313,58.9345%,18696,48.799332
3,4,36736,36735,13,4.31372 seconds,2148,n/17,21702,6927,59.0756%,18102,49.275915
4,5,46077,46076,4,7.25746 seconds,2707,n/17,27206,8722,59.0446%,22574,48.991905
5,6,11036,11035,42,0.331053 seconds,660,n/16,6528,2077,59.1519%,5420,49.111997
6,7,14492,14491,13,0.595155 seconds,864,n/16,8556,2758,59.0395%,7111,49.068452
7,8,23894,23893,8,1.99161 seconds,1406,n/16,14121,4502,59.0985%,11835,49.531263
8,9,15478,15477,5,0.672481 seconds,916,n/16,9142,2932,59.0645%,7604,49.127794
9,10,49603,49602,23,8.9231 seconds,2956,n/16,29291,9418,59.0509%,24328,49.045421

In [4]:
d4b_small = pd.read_csv("../stastistics/stats.csv", sep=',', index_col=False)
d4b_small["leaves/ratio"] = d4b_small["Total Leaves"] / d4b_small["Nodes"] * 100

d4b_small

,Case ID,Nodes,Edges,Starting Node,Duration,Total Colors Used,n/x Ratio,Color 1 Count,Color 2 Count,Color 1 Ratio,Total Leaves,leaves/ratio
0,1,28,27,21,5.1375e-05 seconds,5,n/5,17,7,60.7143%,14,50.000000
1,2,20,19,3,0.00019975 seconds,6,n/3,12,4,60%,10,50.000000
2,3,28,27,3,6.6833e-05 seconds,8,n/3,15,6,53.5714%,14,50.000000
3,4,29,28,18,3.7416e-05 seconds,6,n/4,17,6,58.6207%,14,48.275862
4,5,22,21,18,3.7833e-05 seconds,7,n/3,12,3,54.5455%,12,54.545455
5,6,20,19,9,5.6625e-05 seconds,6,n/3,11,4,55%,9,45.000000
6,7,29,28,6,4.9166e-05 seconds,6,n/4,16,7,55.1724%,10,34.482759
7,8,20,19,3,3.1875e-05 seconds,5,n/4,12,4,60%,10,50.000000
8,9,30,29,10,0.000110209 seconds,8,n/3,17,6,56.6667%,16,53.333333
9,10,20,19,6,4.9333e-05 seconds,7,n/2,13,2,65%,12,60.000000
10,11,25,24,3,7.8125e-05 seconds,6,n/4,15,4,60%,12,48.000000
11,12,21,20,7,5.5083e-05 seconds,5,n/4,12,5,57.1429%,9,42.857143
12,13,29,28,5,4.4834e-05 seconds,7,n/4,15,6,51.7241%,12,41.379310
13,14,27,26,8,5.4125e-05 seconds,7,n/3,16,4,59.2593%,14,51.851852
14,15,24,23,1,4.9209e-05 seconds,6,n/4,13,6,54.1667%,10,41.666667
15,16,30,29,7,9.675e-05 seconds,8,n/3,16,6,53.3333%,15,50.000000
16,17,27,26,4,9.2e-05 seconds,7,n/3,15,6,55.5556%,12,44.444444
17,18,23,22,4,5.45e-05 seconds,6,n/3,14,4,60.8696%,12,52.173913
18,19,20,19,5,5.8459e-05 seconds,6,n/3,11,4,55%,9,45.000000
19,20,22,21,2,4.1625e-05 seconds,6,n/3,13,4,59.0909%,11,50.000000
20,21,28,27,6,8.4792e-05 seconds,7,n/4,16,4,57.1429%,13,46.428571
21,22,20,19,2,2.3417e-05 seconds,5,n/4,12,5,60%,9,45.000000
22,23,20,19,9,4.7208e-05 seconds,5,n/4,11,5,55%,8,40.000000
23,24,25,24,11,4.8167e-05 seconds,6,n/4,14,5,56%,13,52.000000
24,25,30,29,2,7.6416e-05 seconds,7,n/4,18,7,60%,15,50.000000
25,26,29,28,3,8.5084e-05 seconds,6,n/4,18,5,62.069%,14,48.275862
26,27,26,25,8,5.65e-05 seconds,6,n/4,15,6,57.6923%,12,46.153846
27,28,27,26,12,4.7917e-05 seconds,7,n/3,15,5,55.5556%,12,44.444444
28,29,26,25,11,7.6708e-05 seconds,6,n/4,17,4,65.3846%,15,57.692308
29,30,24,23,4,8.3334e-05 seconds,8,n/3,13,5,54.1667%,12,50.000000